export const TABLE_AVAILABILITY_MSG = 'TABLE_AVAILABILITY_MSG';
export const UPDATE_LIST_OF_ALL_TABLES = 'UPDATE_LIST_OF_ALL_TABLES';
export const SET_DATE = 'SET_DATE';
export const CHANGE_WHICH_FORM_PART_IS_VISIBLE =
  'CHANGE_WHICH_FORM_PART_IS_VISIBLE';
export const CHANGE_ANIMATION_STATUS = 'CHANGE_ANIMATION_STATUS';
export const SHOW_TABLE_OPTIONS_MODAL = 'SHOW_TABLE_OPTIONS_MODAL';
export const CHANGE_TABLE_OPTIONS_MODAL_PART =
  'CHANGE_TABLE_OPTIONS_MODAL_PART';
export const MANUALLY_BOOK_A_TABLE = 'MANUALLY_BOOK_A_TABLE';
export const REFETCH_DATA = 'REFETCH_DATA';
export const SEARCH_RESERVATIONS_MODAL = 'SEARCH_RESERVATIONS_MODAL';
export const SEARCH_SINGLE_TABLE_RESERVATIONS_MODAL =
  'SEARCH_SINGLE_TABLE_RESERVATIONS_MODAL';
