export const TABLE_AVAILABILITY_MSG = 'TABLE_AVAILABILITY_MSG';
export const UPDATE_LIST_OF_ALL_TABLES = 'UPDATE_LIST_OF_ALL_TABLES';
export const SET_DATE = 'SET_DATE';
export const CHANGE_WHICH_FORM_PART_IS_VISIBLE =
  'CHANGE_WHICH_FORM_PART_IS_VISIBLE';
export const CHANGE_ANIMATION_STATUS = 'CHANGE_ANIMATION_STATUS';
